<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Hitchpicks</title>

        <link rel="stylesheet" href="/generated/css/global.css">
    </head>
    <body class="flex justify-center items-start p-2">
        <div class="mt-2 bg-gray-800 text-sm text-white rounded-lg p-4" role="alert" tabindex="-1" aria-labelledby="hs-solid-color-dark-label">
            <span id="hs-solid-color-dark-label" class="font-bold">Testing</span> alert! This is to test Tailwind and Preline UI.
        </div>

        <script src="/generated/js/preline.js"></script>
    </body>
</html>